# Generated by Django 5.2.10 on 2026-04-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostype', models.TextField(blank=True, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hashes',
            },
        ),
        migrations.RemoveField(
            model_name='beatmap',
            name='osubeatmapid',
        ),
        migrations.RemoveField(
            model_name='beatmap',
            name='osubeatmapsetid',
        ),
        migrations.AddField(
            model_name='beatmap',
            name='Accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='Length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='Level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='backgroundpath',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='beatmapfile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='beatmapid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='beatmapsetid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='chartfile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='notecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='playcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='pp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='previewpath',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='ranked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='replay_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='speed_multi',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='score',
            name='version',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='cardborder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pfppath',
            field=models.TextField(default='https://qlute.jinkku.moe/static/img/profile/guest.png'),
        ),
        migrations.AddField(
            model_name='user',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='BPM',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='artist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='artist_unicode',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='difficulty',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='mapper',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='ranked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='title_unicode',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
